services:
  # Backend API Service
  - type: web
    name: chainfly-backend
    env: python
    plan: Free
    buildCommand: pip install -r requirements.txt && mkdir -p chainfly-backend/uploads && chmod 755 chainfly-backend/uploads
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120
    envVars:
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: true

  # Frontend Service
  - type: web
    name: chainfly-frontend
    env: static
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://chainfly-backend.onrender.com
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*

        destination: /index.html 
